# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy

on:
  pull_request:
    branches: [main]

jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Global Install tf-next
        run: npm install -g tf-next

      - name: Install dependencies
        run: npm run tf-next

      - name: Terraform Init
        run: terraform -chdir=./deployment/beta init

      # - name: Terraform Plan
      #   run: terraform -chdir=./deployment/beta plan -var-file=./beta.tfvars
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform -chdir=./deployment/beta apply -var-file=./beta.tfvars -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
