# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy

on:
  pull_request:
    branches: [main]

jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Global Install aws sdk
        run: npm install -g tf-next

      - name: Install dependencies
        run: npm ci

      - name: Build and Export Static files
        run: npm run build

      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2
      - run: aws --version
        shell: bash

      # - name: Deploy to Beta
      #   id: install-aws-cli
      #   uses: unfor19/install-aws-cli-action@master
      #   with:
      #     version: ${{ matrix.AWS_CLI_VERSION }}
      # - run: aws --version
      #   shell: bash
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
